/*
 * This file is generated by jOOQ.
 */
package schema;


import schema.tables.Author;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
