/*
 * This file is generated by jOOQ.
 */
package schema;


import schema.tables.Author;
import schema.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
